// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srhjtmmsciywfaehtwsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyaGp0bW1zY2l5d2ZhZWh0d3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTgyMTgsImV4cCI6MjA3MTI3NDIxOH0.M45Yjqo1SF3JqxunQrGeUaOXBLm7CgESyW0rIyzuvVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});