// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aetsstbmwrdxfnygqwsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFldHNzdGJtd3JkeGZueWdxd3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDU0NzIsImV4cCI6MjA3MTM4MTQ3Mn0.58m6a0d_zrJL9AVU0id7kuqdhAacEJ1fBg6JKa3JpVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});